# Docker Compose Override for Development
# This file is automatically loaded with docker-compose.yml
# Usage: docker compose up (automatically includes overrides)

services:
  inventory:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__Rebus=Information
    volumes:
      # Mount source for hot reload (if using development image)
      - ./src/inventory.api:/app/src:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inventory.rule=PathPrefix(`/inventory`)"

  sales:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__Rebus=Information
    volumes:
      # Mount source for hot reload (if using development image)
      - ./src/sales.api:/app/src:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sales.rule=PathPrefix(`/sales`)"

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__Yarp=Information
    volumes:
      # Mount source for hot reload (if using development image)
      - ./src/gateway:/app/src:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/`)"

  # Development-only services
  adminer:
    image: adminer:4.8.1
    container_name: salesapi-adminer
    restart: unless-stopped
    depends_on:
      - sqlserver
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver
      ADMINER_DESIGN: pepa-linha-dark
    ports:
      - "8080:8080"
    networks:
      - salesapi-network
    profiles:
      - dev-tools

  # Redis for caching (development)
  redis:
    image: redis:7.2-alpine
    container_name: salesapi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - salesapi-network
    profiles:
      - caching

volumes:
  redis_data:
    driver: local