version: '3.8'

services:
  inventory:
    build:
      context: .
      dockerfile: src/inventory.api/Dockerfile
    container_name: salesapi-inventory
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=InventoryDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
      - Jwt__Key=ThisIsASecretKeyForJWTTokenGenerationAndValidation2024!
      - Jwt__Issuer=SalesAPI-Gateway
      - Jwt__Audience=SalesAPI-Services
    ports:
      - "5000:8080"
    networks:
      - salesapi-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sales:
    build:
      context: .
      dockerfile: src/sales.api/Dockerfile
    container_name: salesapi-sales
    restart: unless-stopped
    depends_on:
      - inventory
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=SalesDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
      - Services__InventoryApi=http://inventory:8080
      - Jwt__Key=ThisIsASecretKeyForJWTTokenGenerationAndValidation2024!
      - Jwt__Issuer=SalesAPI-Gateway
      - Jwt__Audience=SalesAPI-Services
    ports:
      - "5001:8080"
    networks:
      - salesapi-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: salesapi-gateway
    restart: unless-stopped
    depends_on:
      - inventory
      - sales
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - Jwt__Key=ThisIsASecretKeyForJWTTokenGenerationAndValidation2024!
      - Jwt__Issuer=SalesAPI-Gateway
      - Jwt__Audience=SalesAPI-Services
    ports:
      - "6000:8080"
    networks:
      - salesapi-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  salesapi-network:
    driver: bridge