version: '3.8'

services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: salesapi-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - salesapi-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # SQL Server Database (optional - if you prefer containerized DB)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: salesapi-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Your_password123
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - salesapi-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  rabbitmq_data:
    driver: local
  sqlserver_data:
    driver: local

networks:
  salesapi-network:
    driver: bridge