version: '3.8'

# ===================================================================================================
# SalesAPI Docker Compose Configuration
# This configuration eliminates magic numbers by using environment variables and centralized defaults
# ===================================================================================================

# Shared health check configuration to avoid duplication
x-health-check-defaults: &health-check-defaults
  interval: ${HEALTH_CHECK_INTERVAL:-30s}
  timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
  retries: ${HEALTH_CHECK_RETRIES:-3}
  start_period: ${HEALTH_CHECK_START_PERIOD:-40s}

# Common environment variables shared across services
x-common-env: &common-env
  ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
  ASPNETCORE_URLS: http://+:${CONTAINER_PORT:-8080}
  ConnectionStrings__DefaultConnection: Server=${SQL_HOST:-host.docker.internal};Database=${SQL_DATABASE:-};User Id=${SQL_USERNAME:-sa};Password=${SQL_PASSWORD:-Your_password123};TrustServerCertificate=True
  ConnectionStrings__RabbitMQ: amqp://${RABBITMQ_USERNAME:-admin}:${RABBITMQ_PASSWORD:-admin123}@${RABBITMQ_HOST:-host.docker.internal}:${RABBITMQ_PORT:-5672}/
  Jwt__Key: ${JWT_KEY:-ThisIsASecretKeyForJWTTokenGenerationAndValidation2024!}
  Jwt__Issuer: ${JWT_ISSUER:-SalesAPI-Gateway}
  Jwt__Audience: ${JWT_AUDIENCE:-SalesAPI-Services}

services:
  inventory:
    build:
      context: ../..
      dockerfile: src/inventory.api/Dockerfile
    container_name: salesapi-inventory
    restart: unless-stopped
    environment:
      <<: *common-env
      ConnectionStrings__DefaultConnection: Server=${SQL_HOST:-host.docker.internal};Database=${INVENTORY_DB:-InventoryDb};User Id=${SQL_USERNAME:-sa};Password=${SQL_PASSWORD:-Your_password123};TrustServerCertificate=True
    ports:
      - "${INVENTORY_PORT:-5000}:${CONTAINER_PORT:-8080}"
    networks:
      - salesapi-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      <<: *health-check-defaults
      test: ["CMD", "curl", "-f", "http://localhost:${CONTAINER_PORT:-8080}/health"]

  sales:
    build:
      context: ../..
      dockerfile: src/sales.api/Dockerfile
    container_name: salesapi-sales
    restart: unless-stopped
    depends_on:
      - inventory
    environment:
      <<: *common-env
      ConnectionStrings__DefaultConnection: Server=${SQL_HOST:-host.docker.internal};Database=${SALES_DB:-SalesDb};User Id=${SQL_USERNAME:-sa};Password=${SQL_PASSWORD:-Your_password123};TrustServerCertificate=True
      Services__InventoryApi: http://${INVENTORY_SERVICE_NAME:-inventory}:${CONTAINER_PORT:-8080}
    ports:
      - "${SALES_PORT:-5001}:${CONTAINER_PORT:-8080}"
    networks:
      - salesapi-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      <<: *health-check-defaults
      test: ["CMD", "curl", "-f", "http://localhost:${CONTAINER_PORT:-8080}/health"]

  gateway:
    build:
      context: ../..
      dockerfile: src/gateway/Dockerfile
    container_name: salesapi-gateway
    restart: unless-stopped
    depends_on:
      - inventory
      - sales
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://+:${CONTAINER_PORT:-8080}
      Jwt__Key: ${JWT_KEY:-ThisIsASecretKeyForJWTTokenGenerationAndValidation2024!}
      Jwt__Issuer: ${JWT_ISSUER:-SalesAPI-Gateway}
      Jwt__Audience: ${JWT_AUDIENCE:-SalesAPI-Services}
      # Configure reverse proxy destinations dynamically
      ReverseProxy__Clusters__inventory-cluster__Destinations__destination1__Address: http://${INVENTORY_SERVICE_NAME:-inventory}:${CONTAINER_PORT:-8080}/
      ReverseProxy__Clusters__sales-cluster__Destinations__destination1__Address: http://${SALES_SERVICE_NAME:-sales}:${CONTAINER_PORT:-8080}/
    ports:
      - "${GATEWAY_PORT:-6000}:${CONTAINER_PORT:-8080}"
    networks:
      - salesapi-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      <<: *health-check-defaults
      test: ["CMD", "curl", "-f", "http://localhost:${CONTAINER_PORT:-8080}/health"]

networks:
  salesapi-network:
    driver: bridge